In [6]:
import numpy as np
a=np.random.randint(1,100,24)
b=np.random.randint(1,100,24).reshape(6,4)
print(a)
b

[31  3 66 73 31 45 49 24 93 36 40 40 48 36 92 47 81 51 23 72 23 39  2 62]


array([[69, 70, 79, 36],
       [16, 21, 81, 84],
       [79, 52, 90, 45],
       [58, 64, 69, 82],
       [16, 58, 99, 73],
       [95,  1, 12, 94]], dtype=int32)

In [7]:
np.sort(a)

array([ 2,  3, 23, 23, 24, 31, 31, 36, 36, 39, 40, 40, 45, 47, 48, 49, 51,
       62, 66, 72, 73, 81, 92, 93], dtype=int32)

In [9]:
np.sort(a)[::-1]  ## reverse sort

array([93, 92, 81, 73, 72, 66, 62, 51, 49, 48, 47, 45, 40, 40, 39, 36, 36,
       31, 31, 24, 23, 23,  3,  2], dtype=int32)

In [ ]:
np.sort(b,axis=0) ## axis=0 sort column wise

array([[16,  1, 12, 36],
       [16, 21, 69, 45],
       [58, 52, 79, 73],
       [69, 58, 81, 82],
       [79, 64, 90, 84],
       [95, 70, 99, 94]], dtype=int32)

In [10]:
np.sort(b,axis=1)

array([[36, 69, 70, 79],
       [16, 21, 81, 84],
       [45, 52, 79, 90],
       [58, 64, 69, 82],
       [16, 58, 73, 99],
       [ 1, 12, 94, 95]], dtype=int32)

In [15]:
np.append(a,123)

array([ 31,   3,  66,  73,  31,  45,  49,  24,  93,  36,  40,  40,  48,
        36,  92,  47,  81,  51,  23,  72,  23,  39,   2,  62, 123])

In [ ]:
np.append(b,np.ones((b.shape[0],1)),axis=1)
### np.shape -> (rows,cols)
## np.shape[0] -> rows

array([[69., 70., 79., 36.,  1.],
       [16., 21., 81., 84.,  1.],
       [79., 52., 90., 45.,  1.],
       [58., 64., 69., 82.,  1.],
       [16., 58., 99., 73.,  1.],
       [95.,  1., 12., 94.,  1.]])

In [24]:
np.append(b,np.zeros((1,b.shape[1])),axis=0)

array([[69., 70., 79., 36.],
       [16., 21., 81., 84.],
       [79., 52., 90., 45.],
       [58., 64., 69., 82.],
       [16., 58., 99., 73.],
       [95.,  1., 12., 94.],
       [ 0.,  0.,  0.,  0.]])

In [25]:
## concatinate
c=np.random.randint(1,100,12).reshape(4,3)
d=np.random.randint(1,100,12).reshape(4,3)
print(c)
d

[[95 64 55]
 [76 11 11]
 [83 69 87]
 [19 41 44]]


array([[47, 20, 13],
       [54, 18,  9],
       [51, 59, 48],
       [77, 45, 42]], dtype=int32)

In [26]:
np.concatenate((c,d),axis=1)

array([[95, 64, 55, 47, 20, 13],
       [76, 11, 11, 54, 18,  9],
       [83, 69, 87, 51, 59, 48],
       [19, 41, 44, 77, 45, 42]], dtype=int32)

In [28]:
np.concatenate((c,d),axis=0)

array([[95, 64, 55],
       [76, 11, 11],
       [83, 69, 87],
       [19, 41, 44],
       [47, 20, 13],
       [54, 18,  9],
       [51, 59, 48],
       [77, 45, 42]], dtype=int32)

In [32]:
## unique
z=np.array([1,1,2,1,21,3,4,3,1,3,2,1,3,4,5,6,45,67,65,65,12,21,3,4,5,123])
np.unique(z)

array([  1,   2,   3,   4,   5,   6,  12,  21,  45,  65,  67, 123])

## ✅ np.expand_dims() — What does it do?
It adds a new axis (dimension) to a NumPy array at a specified position.

🤔 Why use it?
To change the shape of an array without changing its data.
This is useful for:

Broadcasting,

Feeding data into models,

Manipulating array shapes safely

In [ ]:
print(a.shape)
np.expand_dims(a,axis=0) ## ->(1,24)shape

(24,)


array([[31,  3, 66, 73, 31, 45, 49, 24, 93, 36, 40, 40, 48, 36, 92, 47,
        81, 51, 23, 72, 23, 39,  2, 62]], dtype=int32)

In [ ]:
np.expand_dims(a,axis=1) ## shape -> (24,1)

array([[31],
       [ 3],
       [66],
       [73],
       [31],
       [45],
       [49],
       [24],
       [93],
       [36],
       [40],
       [40],
       [48],
       [36],
       [92],
       [47],
       [81],
       [51],
       [23],
       [72],
       [23],
       [39],
       [ 2],
       [62]], dtype=int32)

## ✅ np.where() — What is it?
It returns the indices or values where a condition is True.

## np.where(condition, value_if_true, value_if_false)
This returns a new array where:

If condition is true → take value_if_true

If false → take value_if_false

In [ ]:
## np.where()
np.where(a>50) ## return all index

(array([ 2,  3,  8, 14, 16, 17, 19, 23]),)

In [39]:
np.where(a>50,0,a)

array([31,  3,  0,  0, 31, 45, 49, 24,  0, 36, 40, 40, 48, 36,  0, 47,  0,
        0, 23,  0, 23, 39,  2,  0], dtype=int32)

In [41]:
np.where(a%2==0,2,1)

array([1, 1, 2, 1, 1, 1, 1, 2, 1, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 1, 1,
       2, 2])

## ✅ np.argmax() — What is it?
np.argmax() returns the index of the maximum value in a NumPy array.

In [45]:
### np.argmax()
print(np.argmax(a),np.argmin(a))

8 22


In [46]:
print(np.argmax(b,axis=1),np.argmax(b,axis=0))

[2 3 2 3 2 0] [5 0 4 5]


### ✅ np.cumsum() — What is it?
It returns the cumulative sum of elements in an array.

Each element in the output is the sum of all elements before it (including itself).

In [47]:
print(a)
np.cumsum(a)


[31  3 66 73 31 45 49 24 93 36 40 40 48 36 92 47 81 51 23 72 23 39  2 62]


array([  31,   34,  100,  173,  204,  249,  298,  322,  415,  451,  491,
        531,  579,  615,  707,  754,  835,  886,  909,  981, 1004, 1043,
       1045, 1107])

In [48]:
print(b)
np.cumsum(b,axis=0)

[[69 70 79 36]
 [16 21 81 84]
 [79 52 90 45]
 [58 64 69 82]
 [16 58 99 73]
 [95  1 12 94]]


array([[ 69,  70,  79,  36],
       [ 85,  91, 160, 120],
       [164, 143, 250, 165],
       [222, 207, 319, 247],
       [238, 265, 418, 320],
       [333, 266, 430, 414]])

In [50]:
np.cumsum(b,axis=1)

array([[ 69, 139, 218, 254],
       [ 16,  37, 118, 202],
       [ 79, 131, 221, 266],
       [ 58, 122, 191, 273],
       [ 16,  74, 173, 246],
       [ 95,  96, 108, 202]])

In [49]:
np.cumsum(b)

array([  69,  139,  218,  254,  270,  291,  372,  456,  535,  587,  677,
        722,  780,  844,  913,  995, 1011, 1069, 1168, 1241, 1336, 1337,
       1349, 1443])

In [51]:
np.cumprod(a)

array([                  31,                   93,                 6138,
                     448074,             13890294,            625063230,
                30628098270,         735074358480,       68361915338640,
           2461028952191040,    98441158087641600,  3937646323505664000,
        4539582791176355840, -2595716181037154304,  1001784302805975040,
       -8256369989247827968, -4683182475530207232,   965366706183602176,
        3756690168513298432, -6219468972685787136,  4526166217903308800,
       -7946958238866472960,  2552827595976605696, -7745385712836411392])

## ✅ np.percentile() — What is it?
It returns the value below which a given percentage of data falls.

In [53]:
print(a)
np.percentile(a,70)

[31  3 66 73 31 45 49 24 93 36 40 40 48 36 92 47 81 51 23 72 23 39  2 62]


np.float64(52.09999999999998)

In [54]:
### np.histogram
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([2, 0, 3, 5, 6, 1, 2, 2, 1, 2]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

## ✅ np.corrcoef() — What is it?
It calculates the correlation coefficient matrix — typically the Pearson correlation between variables.

# 📌 Pearson Correlation Coefficient (r):
Measures linear relationship between two variables.

Ranges from -1 to 1:

1 = perfect positive correlation

0 = no correlation

-1 = perfect negative correlation

In [55]:
salary=np.array([2000,3000,4000,2500,3500,1500])
experience=np.array([1,2,3,4,5,6])

np.corrcoef(salary,experience)


array([[ 1.        , -0.14285714],
       [-0.14285714,  1.        ]])

### ✅ np.isin() — What is it?
np.isin() checks which elements in an array are present in another list/array.

## ✅ np.flip() — What is it?
np.flip() reverses the order of elements in an array along a specified axis.

In [60]:
arr=np.random.randint(1,20,10)
items=[10,8,15,7,19,12]
print(arr)
arr[np.isin(arr,items)]

[19 17  7  9  6  2 12  1  3 15]


array([19,  7, 12, 15], dtype=int32)

In [61]:
print(a)
np.flip(a)

[31  3 66 73 31 45 49 24 93 36 40 40 48 36 92 47 81 51 23 72 23 39  2 62]


array([62,  2, 39, 23, 72, 23, 51, 81, 47, 92, 36, 48, 40, 40, 36, 93, 24,
       49, 45, 31, 73, 66,  3, 31], dtype=int32)

In [62]:
print(b)
np.flip(b)

[[69 70 79 36]
 [16 21 81 84]
 [79 52 90 45]
 [58 64 69 82]
 [16 58 99 73]
 [95  1 12 94]]


array([[94, 12,  1, 95],
       [73, 99, 58, 16],
       [82, 69, 64, 58],
       [45, 90, 52, 79],
       [84, 81, 21, 16],
       [36, 79, 70, 69]], dtype=int32)

In [67]:
print(np.flip(b,axis=1),"\n\n",np.flip(b,axis=0))

[[36 79 70 69]
 [84 81 21 16]
 [45 90 52 79]
 [82 69 64 58]
 [73 99 58 16]
 [94 12  1 95]] 

 [[95  1 12 94]
 [16 58 99 73]
 [58 64 69 82]
 [79 52 90 45]
 [16 21 81 84]
 [69 70 79 36]]


## ✅ np.put() — Replace elements at specific indices
🔹 Syntax:    np.put(array, indices, values)

array: original array

indices: positions where you want to put values

values: values to insert (can be a single value or list)

In [68]:
print(a)
np.put(a,[1,0,2],[1000,2000,3000])
print(a)


[31  3 66 73 31 45 49 24 93 36 40 40 48 36 92 47 81 51 23 72 23 39  2 62]
[2000 1000 3000   73   31   45   49   24   93   36   40   40   48   36
   92   47   81   51   23   72   23   39    2   62]


### ✅ np.delete() — Remove elements
🔹 Syntax: np.delete(array, obj, axis=None)

array: input array

obj: indices to delete

axis:

None → flatten and delete

0 → delete rows

1 → delete columns

In [73]:
print(a)
np.delete(a,[0,3,4,5])

[2000 1000 3000   73   31   45   49   24   93   36   40   40   48   36
   92   47   81   51   23   72   23   39    2   62]


array([1000, 3000,   49,   24,   93,   36,   40,   40,   48,   36,   92,
         47,   81,   51,   23,   72,   23,   39,    2,   62], dtype=int32)

In [ ]:
## set functions
import numpy as np
m=np.array([1,2,3,4,5])
n=np.array([3,4,5,6,7])

print(np.union1d(m,n))
print(np.intersect1d(n,m))
print(np.setdiff1d(n,m))
print(np.setxor1d(m,n))


[1 2 3 4 5 6 7]
[3 4 5]
[6 7]
[1 2 6 7]
[False False  True False False]


C:\Users\susov\AppData\Local\Temp\ipykernel_17996\3113788305.py:10: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  print(np.in1d(m,3))


## np.clip() is a NumPy function that limits (clips) the values in an array to a specified range.

📌 Syntax: np.clip(array, min_value, max_value)

✅ Meaning:

Any value less than min_value becomes min_value.

Any value greater than max_value becomes max_value.

Values in between remain unchanged.

In [8]:
### np.clip()
a=np.random.randint(1,100,20)
print(a)
np.clip(a,a_max=75,a_min=25)

[50  3 57 27 54 58  8  2 29 28 96 59 18 79 35 27 15 50 76 43]


array([50, 25, 57, 27, 54, 58, 25, 25, 29, 28, 75, 59, 25, 75, 35, 27, 25,
       50, 75, 43], dtype=int32)