# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [12]:
import numpy as np
import random 

arr1=np.array([[random.randint(1,20) for i in range(0,5)] for i in range(0,5)])
print(arr1)


[[ 4  9  7  3  3]
 [11  8  8  6  7]
 [11 16 11 10  1]
 [ 8 10 17 19 18]
 [17  5  9  3 20]]


In [13]:
arr1[:,2]=1
arr1

array([[ 4,  9,  1,  3,  3],
       [11,  8,  1,  6,  7],
       [11, 16,  1, 10,  1],
       [ 8, 10,  1, 19, 18],
       [17,  5,  1,  3, 20]])

In [16]:
arr2=np.arange(1,17).reshape(4,4)
np.fill_diagonal(arr2,0)
arr2


array([[ 0,  2,  3,  4],
       [ 5,  0,  7,  8],
       [ 9, 10,  0, 12],
       [13, 14, 15,  0]])

In [20]:
# 1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
arr3=np.arange(1,37).reshape(6,6)
print(arr3[3:5])
print(arr3[:,2:4])
arr3

[[19 20 21 22 23 24]
 [25 26 27 28 29 30]]
[[ 3  4]
 [ 9 10]
 [15 16]
 [21 22]
 [27 28]
 [33 34]]


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

###  np.concatenate
This is used to join two or more arrays along an axis.
### arr = np.random.randint(0, 100, (5, 5))
This creates a 5x5 NumPy array with random integers between 0 and 99.

⚠️ Key Rule:
For axis=0: all arrays must have same number of columns.

For axis=1: all arrays must have same number of rows.

In [ ]:
arr2=np.random.randint(1,100,(5,5))

array([[86, 23, 15, 80, 92],
       [31, 98, 34, 64, 37],
       [50, 46, 49, 58, 43],
       [48,  3, 16, 33, 72],
       [55, 72, 86, 36, 78]], dtype=int32)

In [23]:
arr1=np.random.randint(1,100,(3,4))
arr2=np.random.randint(1,100,(3,4))

print("add - ",arr1+arr2)
print("sub - ",arr1-arr2)
print("mul - ",arr1*arr2)
print(" div - ",arr1/arr2)

add -  [[ 63  75 101  58]
 [ 91  20 136  82]
 [133  95  39 110]]
sub -  [[ -3  33   1 -52]
 [-71 -14 -28  12]
 [-23 -19 -25 -44]]
mul -  [[ 990 1134 2550  165]
 [ 810   51 4428 1645]
 [4290 2166  224 2541]]
 div -  [[0.90909091 2.57142857 1.02       0.05454545]
 [0.12345679 0.17647059 0.65853659 1.34285714]
 [0.70512821 0.66666667 0.21875    0.42857143]]


In [ ]:
arr1=np.arange(1,10).reshape(3,3)

m=arr1.mean()
s=arr1.std()

Normalized_arr=(arr1-m)/s

Normalized_arr

array([[-1.54919334, -1.161895  , -0.77459667],
       [-0.38729833,  0.        ,  0.38729833],
       [ 0.77459667,  1.161895  ,  1.54919334]])

In [29]:
arr2=np.random.randint(1,100,(4,4))

print(arr2.sum(axis=1))
print(arr2.sum(axis=0))

[134 222 114 234]
[251  96 179 178]


In [ ]:
arr=np.random.randint(1,10,(3,3))
print(arr)

a=np.array([1,2,3]) ## 1d


result=arr+a ## brodcust in each row
result

[[1 5 7]
 [1 6 6]
 [1 8 5]]


array([[ 2,  7, 10],
       [ 2,  8,  9],
       [ 2, 10,  8]])

In [38]:
arr=np.random.randint(1,10,(4,4))
print(arr)

a=np.array([1,2,3,4]).reshape(4,1)
print(a,np.shape(a))

result=arr-a
print(result)

[[6 7 8 3]
 [8 8 3 1]
 [3 6 2 7]
 [2 2 8 4]]
[[1]
 [2]
 [3]
 [4]] (4, 1)
[[ 5  6  7  2]
 [ 6  6  1 -1]
 [ 0  3 -1  4]
 [-2 -2  4  0]]


In [ ]:
### liner algebra -> linalg

arr=np.array([[ 2,  7, 10],
       [ 2,  8,  9],
       [ 2, 10,  8]])

dt=np.linalg.det(arr)
print(dt) ### determinant

if dt!=0:
    print(np.linalg.inv(arr)) ### inverse 
else:
    print("has no inverse")

eigenvalues, eigenvectors = np.linalg.eig(arr)
print("\nEigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


2.000000000000003
[[-13.   22.   -8.5]
 [  1.   -2.    1. ]
 [  2.   -3.    1. ]]

Eigenvalues: [19.44523111 -0.07506613 -1.37016498]
Eigenvectors:
 [[ 0.56890876  0.98548319 -0.83302018]
 [ 0.56748136 -0.07352845 -0.28032159]
 [ 0.59523753 -0.15302436  0.47696666]]


In [43]:
arr1=np.random.randint(1,10,(3,4))
arr2=np.random.randint(1,10,(4,3))
print(" dot product - \n", np.dot(arr1,arr2))  ### matrix multiplaction


 dot product - 
 [[ 56  45 106]
 [ 77  69 115]
 [ 99  89 131]]


In [50]:
a = np.array([[2, 1, 3],
                   [1, 0, 2],
                   [4, 1, 8]])
a1=a.reshape(1,9)
print(a1)
a2=a.reshape(9,1)
print(a2)

[[2 1 3 1 0 2 4 1 8]]
[[2]
 [1]
 [3]
 [1]
 [0]
 [2]
 [4]
 [1]
 [8]]


In [49]:
arr2 = np.random.randint(1, 100, size=(5, 5))
print(arr2)

flatt=arr2.flatten()
print(flatt)
arr2=flatt.reshape(5,5)
print(arr2)

[[37 45 75 41 98]
 [38 66 87 26 20]
 [22 63 62 72 75]
 [19 26 45 58 11]
 [32 21 22 12 99]]
[37 45 75 41 98 38 66 87 26 20 22 63 62 72 75 19 26 45 58 11 32 21 22 12
 99]
[[37 45 75 41 98]
 [38 66 87 26 20]
 [22 63 62 72 75]
 [19 26 45 58 11]
 [32 21 22 12 99]]


In [67]:
arr=np.random.randint(1,100,(5,5))
print(arr)

corners=arr[[0,0,-1,-1],[0,-1,0,-1]]
print(corners)

""" 
✅ Why this works:
arr1[[0, 0, -1, -1], [0, -1, 0, -1]]

First list [0, 0, -1, -1] specifies the row indices:

Row 0, Row 0, Row -1 (last row), Row -1 (last row).

Second list [0, -1, 0, -1] specifies the column indices:

Column 0, Column -1 (last column), Column 0, Column -1 (last column).

These are paired together:

(0, 0) → Top-left corner

(0, -1) → Top-right corner

(-1, 0) → Bottom-left corner

(-1, -1) → Bottom-right corner

"""

[[85 37 41 17 76]
 [17 70 64 19 74]
 [61 81 76 96 97]
 [15 21 78 93 66]
 [ 8 87 23 16 89]]
[85 76  8 89]


' \n✅ Why this works:\narr1[[0, 0, -1, -1], [0, -1, 0, -1]]\n\nFirst list [0, 0, -1, -1] specifies the row indices:\n\nRow 0, Row 0, Row -1 (last row), Row -1 (last row).\n\nSecond list [0, -1, 0, -1] specifies the column indices:\n\nColumn 0, Column -1 (last column), Column 0, Column -1 (last column).\n\nThese are paired together:\n\n(0, 0) → Top-left corner\n\n(0, -1) → Top-right corner\n\n(-1, 0) → Bottom-left corner\n\n(-1, -1) → Bottom-right corner\n\n'

In [68]:
print(arr)
arr[arr>50]=101
print(arr)

[[85 37 41 17 76]
 [17 70 64 19 74]
 [61 81 76 96 97]
 [15 21 78 93 66]
 [ 8 87 23 16 89]]
[[101  37  41  17 101]
 [ 17 101 101  19 101]
 [101 101 101 101 101]
 [ 15  21 101 101 101]
 [  8 101  23  16 101]]


### np.dtype([...]): Defines a custom data type where each entry has fields (like columns in a table).

Fields:

'name': Unicode string up to 10 characters (U10).

'age': 4-byte integer (i4).

'weight': 4-byte float (f4).

So this creates a data type like a record or table row.

when defining the dtype?

This creates a structured data type in NumPy. It tells NumPy:
💬 “This array is not just numbers or strings – it’s like a table where each row has multiple named fields (columns), and every field has its own type.”

### np.sort(..., order='age') tells NumPy:

“Sort all rows using the age field as the key.”


In [ ]:
#### custome data type
dt=np.dtype([('name','U10'),("age","i4"),("weight","f4")])

data=np.array([
        ('Alice', 25, 55.5),
        ('Bob', 30, 70.2),
        ('Charlie', 22, 68.0)
],dtype=dt)

print(data)

sort_age_data=np.sort(data,order="age")
print(sort_age_data)


[('Alice', 25, 55.5) ('Bob', 30, 70.2) ('Charlie', 22, 68. )]
[('Charlie', 22, 68. ) ('Alice', 25, 55.5) ('Bob', 30, 70.2)]
