### Numpy 
NumPy (Numerical Python) is a powerful library in Python for:
Handling large arrays and matrices.
Performing mathematical operations on arrays efficiently.
It’s much faster than using Python lists for numerical tasks because it is implemented in C under the hood.

You’ll use it for:
✅ Data analysis
✅ Machine learning
✅ Scientific computing
✅ Image processing

| **Method**                           | **What It Does**                                            |
| ------------------------------------ | ----------------------------------------------------------- |
| `np.array()`                         | Create a NumPy array from a list, tuple, or other sequence. |
| `np.arange(start, stop)`             | Create a range of numbers as a NumPy array.                 |
| `np.reshape(shape)`                  | Change the shape of an array without changing its data.     |
| `np.random.randint(low, high, size)` | Generate random integers in a specified range.              |
| `np.diag()`                          | Extract or create diagonal elements of a matrix.            |
| `np.fill_diagonal(arr, value)`       | Replace diagonal elements with a specified value.           |
| `arr[:, col]`                        | Select all rows for a specific column (column slicing).     |
| `arr[row, :]`                        | Select all columns for a specific row (row slicing).        |
| `arr[rows, cols]`                    | Fancy indexing to select specific rows and columns.         |
| `arr.flatten()`                      | Flatten a multi-dimensional array into a 1D array.          |
| `arr.sum(axis=0)`                    | Sum values along columns.                                   |
| `arr.sum(axis=1)`                    | Sum values along rows.                                      |
| `arr.mean()`                         | Compute mean of all elements.                               |
| `arr.std()`                          | Compute standard deviation.                                 |
| `arr.var()`                          | Compute variance.                                           |
| `np.linalg.det()`                    | Compute determinant of a matrix.                            |
| `np.linalg.inv()`                    | Compute inverse of a matrix.                                |
| `np.linalg.eig()`                    | Compute eigenvalues and eigenvectors of a matrix.           |
| `arr + scalar`                       | Broadcasting: add scalar to all elements of the array.      |
| `arr - scalar`                       | Broadcasting: subtract scalar from all elements.            |
| `np.where(condition, x, y)`          | Return elements based on a condition.                       |
| `arr[arr > value] = new_value`       | Boolean indexing: Replace all values satisfying condition.  |
| `np.concatenate([arr1, arr2], axis)` | Join arrays along a given axis.                             |
| `np.hstack([arr1, arr2])`            | Horizontally stack arrays.                                  |
| `np.vstack([arr1, arr2])`            | Vertically stack arrays.                                    |
| `np.dtype()`                         | Define custom data types for structured arrays.             |
| `np.sort(arr, order='field')`        | Sort a structured array by a specific field.                |
| `np.sqrt(arr)`                       | Compute square root of array elements.                      |
| `np.eye(N)`                          | Create an identity matrix of size N x N.                    |
| `np.ma.masked_array()`               | Create a masked array where some data is hidden.            |
| `np.ma.masked_where()`               | Mask array elements where a condition is true.              |
| `np.ma.filled()`                     | Replace masked elements with a specified fill value.        |


In [1]:
import numpy as np

arr1=np.array([1,2,3,4,56,5])  ## 1D array
print(type(arr1),arr1.shape)
print(arr1.ndim)  #1D


<class 'numpy.ndarray'> (6,)
1


In [3]:

arr2=arr1.reshape(2,3)  ## 1 row 6 cols
print(arr2.shape)
arr2

(2, 3)


array([[ 1,  2,  3],
       [ 4, 56,  5]])

In [ ]:
## atributes
arr2=np.array([[1,3,5,7],[2,4,6,8],[12,45,78,29]])  ## 2D array
print(arr2.shape)
print(arr2)
print(f"size - ",arr2.size)
print(f"no. of dimensions - {arr2.ndim}")
print(F"data type : {arr2.dtype}")
print("Item size - ",arr2.itemsize)  

(3, 4)
[[ 1  3  5  7]
 [ 2  4  6  8]
 [12 45 78 29]]
size -  12
no. of dimensions - 2
data type : int64
Item size -  8


In [11]:
np.arange(1,20,2).reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [ ]:
np.ones((3,5))   ## create matrix of 3 rows and 5 cols and all the elements are 1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.eye(4) ## create identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
### list in python
list1=[1,3,5,7,9]
list2=[2,4,6,8,10]

print("add - ",list1+list2)

add -  [1, 3, 5, 7, 9, 2, 4, 6, 8, 10]


In [ ]:
### numpy vectorized Operations 
arr1=np.array([1,3,5,7,9])
arr2=np.array([2,4,6,8,10])

## element wise add , sub ,mul, div  and return type also a array
print("add - ",arr1+arr2)
print("sub - ",arr1-arr2)
print("mul - ",arr1*arr2)
print(" div - ",arr1/arr2)

add -  [ 3  7 11 15 19]
sub -  [-1 -1 -1 -1 -1]
mul -  [ 2 12 30 56 90]
 div -  [0.5        0.75       0.83333333 0.875      0.9       ]


In [7]:
## universal function
arr=np.array([1,2,4,5,6])

print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))

[1.         1.41421356 2.         2.23606798 2.44948974]
[  2.71828183   7.3890561   54.59815003 148.4131591  403.42879349]
[ 0.84147098  0.90929743 -0.7568025  -0.95892427 -0.2794155 ]
[0.         0.69314718 1.38629436 1.60943791 1.79175947]


In [15]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr,arr[0][2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 3


In [ ]:
""" 
[[7, 8]
[11,12]]
"""
print(arr[1:,2:])
print(arr[:2,2:])

[[ 7  8]
 [11 12]]
[]


In [17]:
## modifly elemts 
arr[0,0]=100
arr[2][2]=99
print(arr)

arr[1:]=1
print(arr)

arr[:2,2:]=0
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  99  12]]
[[100   2   3   4]
 [  1   1   1   1]
 [  1   1   1   1]]
[[100   2   0   0]
 [  1   1   0   0]
 [  1   1   1   1]]


### Mean of data
The mean is the average of all numbers.

### std Standard Deviation
It measures how spread out the numbers are from the mean.

### Normalization?
Normalization is a way to scale your data so that it fits within a specific range.
This is very important in machine learning because:
✅ It makes models converge faster.
✅ It avoids features with big values dominating features with small values.
Result: Mean = 0, Std Dev = 1.

### median
The median is the middle value when data is sorted.
If there are an odd number of data points → it’s the middle one.
If there are an even number of data points → it’s the average of the two middle values.

### varient 
Variance measures how far the numbers are spread out from the mean (μ).


In [24]:
data=np.array([1,3,5,7,9])

mean=np.mean(data)   ## avg
std=np.std(data) # standard deviation

normalized_data=(data-mean)/std  ## mean=0 , std=1

print(normalized_data)
print(f"after normalization mean is = {np.mean(normalized_data)}, std is = {np.std(normalized_data)}")

print(f"mean : {mean}, std : {std}")
print("median : ",np.median(data))
print("Varient : ",np.var(data))

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
after normalization mean is = 0.0, std is = 0.9999999999999999
mean : 5.0, std : 2.8284271247461903
median :  5.0
Varient :  8.0


In [38]:
data=np.arange(1,11)
print(data)
print(data<5) ## return  bool array
print(data[data<=5])

[ 1  2  3  4  5  6  7  8  9 10]
[ True  True  True  True False False False False False False]
[1 2 3 4 5]


In [7]:
ages=np.array([12,34,67,32,7,19,22,23,21,22]) ## max age 100
print(ages.dtype) ## int 64
ages=ages.astype(np.int32) ## new array return
ages.dtype

int64


dtype('int32')

In [13]:
arr=np.array([[34,67,32,70,19,22,23,21],[67,32,7,19,22,23,90,89]])
arr**2

array([[1156, 4489, 1024, 4900,  361,  484,  529,  441],
       [4489, 1024,   49,  361,  484,  529, 8100, 7921]])

In [11]:
arr>50

array([[False,  True, False,  True, False, False, False, False],
       [ True, False, False, False, False, False,  True,  True]])

In [14]:
arr1=np.array([[4,6,3,7,9,2,1,2],[7,2,7,9,2,3,0,8]])

arr1 * arr

array([[136, 402,  96, 490, 171,  44,  23,  42],
       [469,  64,  49, 171,  44,  69,   0, 712]])

In [20]:
np.max(arr,axis=0) ## 0 -> col 

array([67, 67, 32, 70, 22, 23, 90, 89])

In [21]:
print(np.prod(arr))
np.prod(arr,axis=1)  ## 1 - row

6244971992884346880


array([1030208551680, 1155738165120])

In [102]:
a1=np.arange(0,12).reshape(3,4)
a2=np.arange(12,24).reshape(4,3)
print(a1,"\n",a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 
 [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [103]:
print(np.transpose(a1))

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [106]:
a2.T

array([[12, 15, 18, 21],
       [13, 16, 19, 22],
       [14, 17, 20, 23]])

In [107]:
## ravel -> convert into 1D array
a2.ravel()

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [29]:
np.dot(a1,a2) ## matrix dot product

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [31]:
np.log(a1)

C:\Users\susov\AppData\Local\Temp\ipykernel_13344\2387409814.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

In [43]:
np.round(np.random.random((2,3))*100)

array([[54., 12., 36.],
       [76., 97., 89.]])

In [45]:
np.ceil(np.random.random((2,3))*100)

array([[55., 46., 86.],
       [27., 82., 36.]])

In [ ]:
arr=np.array([[34,67,32,70,19,22,23,21],[67,32,7,19,22,23,90,89],[67,32,7,19,22,23,90,89]])
print(arr[1],arr[1,2])


[67 32  7 19 22 23 90 89] 7


In [90]:
arr3=np.arange(27).reshape(3,3,3)
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [95]:
# np.nditer(arr3) -> convert into 1D array
for i in np.nditer(arr3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [93]:
arr3=np.arange(27).reshape(3,3,3)
for i in arr3:
    print(arr3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [87]:
arr3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [82]:
arr3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [83]:
arr3[1,1,2::2]

array([14])

In [85]:
arr3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [57]:
arr=np.array([[34,67,32,70,19,22,23,21],[67,32,7,19,22,23,90,89],[67,32,7,19,22,23,90,89]])
print(arr)


[[34 67 32 70 19 22 23 21]
 [67 32  7 19 22 23 90 89]
 [67 32  7 19 22 23 90 89]]


In [66]:
print(arr[::2,::7],arr[0:2,::2])

[[34 21]
 [67 89]] [[34 32 19 23]
 [67  7 22 90]]


In [62]:
arr[::2,3::3]

array([[70, 23],
       [19, 90]])

In [58]:
arr[1:,3:7]

array([[19, 22, 23, 90],
       [19, 22, 23, 90]])

In [54]:
arr[1,2:7]

array([ 7, 19, 22, 23, 90])

In [55]:
arr[:,2:5]

array([[32, 70, 19],
       [ 7, 19, 22]])

In [ ]:
a3=np.arange(12).reshape(3,4)
a1=np.arange(12,24).reshape(3,4)
np.hstack((a1,a3)) ## horinzontaily 

array([[12, 13, 14, 15,  0,  1,  2,  3],
       [16, 17, 18, 19,  4,  5,  6,  7],
       [20, 21, 22, 23,  8,  9, 10, 11]])

In [ ]:
np.vstack((a3,a1)) ### verticaly

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [115]:
## splition

np.hsplit(a1,2)

[array([[12, 13],
        [16, 17],
        [20, 21]]),
 array([[14, 15],
        [18, 19],
        [22, 23]])]

In [116]:
np.vsplit(a3,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

✅ 1. np.eye()
Creates a 2D array with 1s on the diagonal and 0s elsewhere (identity matrix).

np.eye(3) → 3x3 identity matrix.

✅ 2. np.fill_diagonal()
Directly fills the diagonal elements of an array with a given value.

Useful for modifying the diagonal quickly.

✅ 3. np.concatenate()
Combines multiple arrays along a specified axis.

axis=0: Stack rows, axis=1: Stack columns.

✅ 3. np.random.randint()
Generates random integers between a given range.

Example: np.random.randint(1, 20, size=(5, 5)).

✅ 4. Broadcasting
Lets you perform operations between arrays of different shapes without explicit looping.

Example: Adding a 1D array to each row/column of a 2D array.

✅ 5. np.linalg.det()
Computes the determinant of a matrix.

✅ 6. np.linalg.inv()
Computes the inverse of a matrix (if invertible).

✅ 7. np.linalg.eig()
Computes the eigenvalues and eigenvectors of a square matrix.

✅ 5. Fancy Indexing
Allows you to pick multiple specific elements at once using index arrays.

Example: arr[[0, 0, -1, -1], [0, -1, 0, -1]] → corners.

✅ 8. np.reshape()
Changes the shape of an array without changing its data.

✅ 9. flatten()
Converts a multi-dimensional array into a 1D array.

✅ 10. Fancy indexing
Access multiple specific elements using arrays of indices.

Example: arr[[0, 2], [1, 3]].

✅ 11. Boolean indexing
Select or modify elements of an array based on a condition.

Example: arr[arr > 10].

✅ 12. Structured Arrays
Arrays with named fields (like name, age, etc.) for mixed data types.

ex : dt = np.dtype([('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])

Use np.dtype() to define structure.

✅ 13. np.sort(..., order='field')
Sorts a structured array by a specified field.

✅ 14. np.sqrt()
Computes the square root element-wise.

✅ 15. numpy.ma.masked_array()
Creates a masked array where certain elements are hidden/masked based on a condition or mask array.

✅ 16. np.random.randint()
Generates random integers within a range.

✅ 17. np.random.rand()
Generates random floats in the range [0, 1).

✅ 18. Masking with np.eye(..., dtype=bool)
Creates a boolean mask for diagonals (True on diagonal, False elsewhere).

✅ 19. mean(axis=...), sum(axis=...)
Aggregates values across rows or columns.

✅ 20. np.arange()
Creates a sequence of numbers with a specified start, stop, and step.

✅ 21. np.shape
Returns the shape (dimensions) of an array.

