### Numpy 
NumPy (Numerical Python) is a powerful library in Python for:
Handling large arrays and matrices.
Performing mathematical operations on arrays efficiently.
It’s much faster than using Python lists for numerical tasks because it is implemented in C under the hood.

You’ll use it for:
✅ Data analysis
✅ Machine learning
✅ Scientific computing
✅ Image processing

In [ ]:
import numpy as np

arr1=np.array([1,2,3,4,56,5])  ## 1D array
print(type(arr1),arr1.shape)
print(arr1.ndim)  #1D


<class 'numpy.ndarray'> (6,)
1


In [3]:

arr2=arr1.reshape(2,3)  ## 1 row 6 cols
print(arr2.shape)
arr2

(2, 3)


array([[ 1,  2,  3],
       [ 4, 56,  5]])

In [ ]:
## atributes
arr2=np.array([[1,3,5,7],[2,4,6,8],[12,45,78,29]])  ## 2D array
print(arr2.shape)
print(arr2)
print(f"size - ",arr2.size)
print(f"no. of dimensions - {arr2.ndim}")
print(F"data type : {arr2.dtype}")
print("Item size - ",arr2.itemsize)  

(3, 4)
[[ 1  3  5  7]
 [ 2  4  6  8]
 [12 45 78 29]]
size -  12
no. of dimensions - 2
data type : int64
Item size -  8


In [11]:
np.arange(1,20,2).reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [ ]:
np.ones((3,5))   ## create matrix of 3 rows and 5 cols and all the elements are 1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.eye(4) ## create identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
### list in python
list1=[1,3,5,7,9]
list2=[2,4,6,8,10]

print("add - ",list1+list2)

add -  [1, 3, 5, 7, 9, 2, 4, 6, 8, 10]


In [ ]:
### numpy vectorized Operations 
arr1=np.array([1,3,5,7,9])
arr2=np.array([2,4,6,8,10])

## element wise add , sub ,mul, div  and return type also a array
print("add - ",arr1+arr2)
print("sub - ",arr1-arr2)
print("mul - ",arr1*arr2)
print(" div - ",arr1/arr2)

add -  [ 3  7 11 15 19]
sub -  [-1 -1 -1 -1 -1]
mul -  [ 2 12 30 56 90]
 div -  [0.5        0.75       0.83333333 0.875      0.9       ]


In [7]:
## universal function
arr=np.array([1,2,4,5,6])

print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))

[1.         1.41421356 2.         2.23606798 2.44948974]
[  2.71828183   7.3890561   54.59815003 148.4131591  403.42879349]
[ 0.84147098  0.90929743 -0.7568025  -0.95892427 -0.2794155 ]
[0.         0.69314718 1.38629436 1.60943791 1.79175947]


In [15]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr,arr[0][2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 3


In [ ]:
""" 
[[7, 8]
[11,12]]
"""
print(arr[1:,2:])
print(arr[:2,2:])

[[ 7  8]
 [11 12]]
[]


In [17]:
## modifly elemts 
arr[0,0]=100
arr[2][2]=99
print(arr)

arr[1:]=1
print(arr)

arr[:2,2:]=0
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  99  12]]
[[100   2   3   4]
 [  1   1   1   1]
 [  1   1   1   1]]
[[100   2   0   0]
 [  1   1   0   0]
 [  1   1   1   1]]


### Mean of data
The mean is the average of all numbers.

### std Standard Deviation
It measures how spread out the numbers are from the mean.

### Normalization?
Normalization is a way to scale your data so that it fits within a specific range.
This is very important in machine learning because:
✅ It makes models converge faster.
✅ It avoids features with big values dominating features with small values.
Result: Mean = 0, Std Dev = 1.

### median
The median is the middle value when data is sorted.
If there are an odd number of data points → it’s the middle one.
If there are an even number of data points → it’s the average of the two middle values.

### varient 
Variance measures how far the numbers are spread out from the mean (μ).


In [24]:
data=np.array([1,3,5,7,9])

mean=np.mean(data)   ## avg
std=np.std(data) # standard deviation

normalized_data=(data-mean)/std  ## mean=0 , std=1

print(normalized_data)
print(f"after normalization mean is = {np.mean(normalized_data)}, std is = {np.std(normalized_data)}")

print(f"mean : {mean}, std : {std}")
print("median : ",np.median(data))
print("Varient : ",np.var(data))

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
after normalization mean is = 0.0, std is = 0.9999999999999999
mean : 5.0, std : 2.8284271247461903
median :  5.0
Varient :  8.0


In [38]:
data=np.arange(1,11)
print(data)
print(data<5) ## return  bool array
print(data[data<=5])

[ 1  2  3  4  5  6  7  8  9 10]
[ True  True  True  True False False False False False False]
[1 2 3 4 5]
